### PR TITLE
Add fedora37

### PR DESCRIPTION
**Pull request by johanneskastl**
Add Fedora37 variables and adjust loading of variables.

Loading the variables is not really nice, since the existing code uses `ansible_os_family == "RedHat"`, which also matches Fedora. If desired I could rework that to use e.g. `first_found` or similar.

### CODE REVIEW

**Review by jvoss — APPROVED** [review]

**Comment by jvoss** [comment]
Updated the testing and documentation to include Fedora 37. However the checks seem to be failing on the installation step where the `upgrade.sh` netbox script is ran:

```
"Failed to build Pillow"
```

Are there any additional Python packages or steps for Fedora that need to be added to make this work on a fresh install?

**Comment by johanneskastl** [comment]
> Updated the testing and documentation to include Fedora 37. However the checks seem to be failing on the installation step where the `upgrade.sh` netbox script is ran:
> 
> ```
> "Failed to build Pillow"
> ```
> 
> Are there any additional Python packages or steps for Fedora that need to be added to make this work on a fresh install?

I used the `generic/fedora37` vagrant box and it worked with the changes from my PR. But as I am using some more roles before (to setup redis and postgresql) it might be that those are pulling in packages. I'll have a look.

**Comment by jvoss** [comment]
I wonder if it could be related to this thread: [python-pillow fails to build with Python 3.11](https://bugzilla.redhat.com/show_bug.cgi?id=2027388)

If I follow correctly, they worked around it by using Python 3.10. I'm wondering what implications need to be considered if we set the Python version for Fedora 37 to `3.10` instead of `3.11`. Thoughts?

**Comment by johanneskastl** [comment]
> If I follow correctly, they worked around it by using Python 3.10. I'm wondering what implications need to be considered if we set the Python version for Fedora 37 to `3.10` instead of `3.11`. Thoughts?

Not sure why I do not see this on my local machine during testing.

But I just pushed a commit changing Fedora37 from python3.11 to python3.10, which also worked fine on my local machine. Let's see what the CI says...

**Comment by jvoss** [comment]
> 
> But I just pushed a commit changing Fedora37 from python3.11 to python3.10, which also worked fine on my local machine. Let's see what the CI says...

That seemed to do the trick. Anything else you think we should try or do you think this would suffice enough for merge?

**Comment by johanneskastl** [comment]
> That seemed to do the trick. Anything else you think we should try or do you think this would suffice enough for merge?

As it seems to work both locally and in the CI, I think we can safely merge it.

**Pull request merged**
